---

- name: Download kind to specified location {{ kind_install_dir }}
  get_url:
    url: "{{ kind_repo }}"
    dest: "{{ kind_install_dir }}/kind"
    mode: 0755
    force: true
  become: true
  tags:
    - install


- name: Installation has been finished
  debug:
    msg: "Installation of kind version {{ kind_version }} has been finished!"
  tags:
    - install

- name: "install kubectl"
  shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  when: not kubectl_state.stat.exists
  tags:
    - install

- name: "change kubectl permission"
  shell: chmod +x kubectl
  become: yes
  when: not kubectl_state.stat.exists
  tags:
    - install

    
- name: "move kubectl "
  shell: mv kubectl /usr/local/bin/
  become: yes
  when: not kubectl_state.stat.exists
  tags:
    - install