---

# ####################################################################
#                             Prechecks
# ####################################################################

- name: Prechecks
  include_tasks: precheck.yml
  tags:
    - always

# ####################################################################
#                             Install kind
# ####################################################################

- name: Install kind
  include_tasks: install.yml
  when: kind_version != kind_installed_version.stdout
  tags:
    - install

# ####################################################################
#                             Create cluster
# ####################################################################

- name: Create cluster {{ cluster_name }}
  include_tasks: create-cluster.yml
  tags:
    - create

# ####################################################################
#                             Delete cluster
# ####################################################################

- name: Delete cluster {{ cluster_name }}
  include_tasks: delete-cluster.yml
  tags:
    - delete